### ISSUE TITLE
WIndows 10 Install Error

### ISSUE THREAD

**Issue by eric2952** [neilSchroeder/vscode-theme-bladerunner#1]
```
The 1 extension(s) below, in workspace recommendations have issues: undefined.dark (not found in marketplace)
```
I tried installing this on windows 10 and got the above code. Unable to enable through extensions view

**Comment by neilSchroeder** [comment]
Thanks for the feedback! This appears to have been a problem with the naming of the package in it's configuration file. I've fixed the issue. Try pulling the repository again and let me know if it works.

**Comment by eric2952** [comment]
This appears to have resolved the issue, thanks!
